@startuml
'https://plantuml.com/class-diagram

class Member {
e-mail: String
}
class BoardMember {
}
class Event {
date: Date
description: String
assign(I: Location): void
}
class Conference {
max_attendees: Integer
}
class BoardMeeting {
}
class Location {
description: String
address: String
}
class Person {
name: String
}
class AAUOC {
newLocation(I: Location): void
newEvent(e: Event): void
newPerson(p: Person): void
informEvent(e: Event): void
register(m: Member,e: Event): void
}

AAUOC o--- Location
AAUOC o--- Event
AAUOC o--- Person

Person <|-- Member
BoardMember -|> Member

BoardMeeting --|> Event

Event -- Member : attends To

BoardMember -- BoardMeeting : attends To

Location --> Event : isLocated in

Conference --|> Event
Conference -- Person : attends To

@enduml