@startuml
'https://plantuml.com/class-diagram

class Member {
}
class BoardMember {
}
class Event {
}
class Conference {
}
class BoardMeeting {
}
class Location {
}
class Person {
}
class AAUOC {
}

AAUOC o-- Location
AAUOC o-- Event
AAUOC o-- Person


BoardMeeting --|> Event

Event --- Member

Member --|> Person

BoardMember --|> Member

BoardMember --- BoardMeeting

Conference --|> Event
Conference --- Person

@enduml